config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root 'projects#index'

  resources :messages, only: :create
  resources :projects, only: [:show, :edit, :create, :new]
  get '/about' => 'application#about', as: "about"

  get '/invitations' => 'projects#invitations', as: 'invitations'
  get '/my_projects' => 'projects#my_projects', as: 'my_projects'
  get '/my_teams' => 'projects#my_teams', as: 'my_teams'
  get '/pending_applications' => 'projects#pending_applications', as: 'pending_applications'
  get '/finished_projects' => 'projects#finished_projects', as: 'finished_projects'

  post 'approve_collaboration' => 'user_projects#approve_collaboration', as: "approve_collaboration"  
  post 'deny_collaboration' => 'user_projects#deny_collaboration', as: "deny_collaboration"  
  post 'apply_for_project' => 'user_projects#apply_for_project', as: 'apply_for_project'
  post 'invite' => 'user_projects#invite', as: 'invite'
  post 'accept_invitation' => 'user_projects#accept_invitation', as: 'accept_invitation'
  post 'leave_project' => 'user_projects#leave_project', as: 'leave_project'
  post 'remove_user_from_project' => 'user_projects#remove_user_from_project', as: 'remove_user_from_project'
  post 'close_project' => 'user_projects#close_project', as: 'close_project'
  post 'in_progress' => 'user_projects#in_progress', as: 'in_progress'
  post 'update' => 'user_projects#update', as: 'update'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if user_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= image_tag avatar_url(current_user), id: "gravatar" %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Dashboard", current_user %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path, {class: "edit_account_link"} %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </li>
      </ul>
  </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><%= link_to current_user.name, current_user %></a></li>
    <li><%= link_to "Start a new Project", new_project_path %></li>
    <li><%= link_to "My Projects", my_projects_path %>
    <li><%= link_to "My Current Teams", my_teams_path %></li>
    <li><%= link_to "Pending Applications", pending_applications_path %></li>
    <li><%= link_to "Invitations", invitations_path %></li>
    <li><%= link_to "Finished Projects", finished_projects_path %></a></li>
    <li><%= link_to "Edit Account", edit_user_registration_path, class: "edit_account_link" %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectFinder</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <% if user_signed_in? %>
      <%= render 'layouts/sidebar' %>
    <% end %>
    <div class="container-fluid">
      <div class="row">

        <% if notice %>
          <p class="alert alert-success col-sm-offset-3 col-md-8"><%= notice %></p>
        <% end %>
        <% if flash[:message] %>
          <% flash[:message].each do |message| %>
            <p class="alert alert-success col-sm-offset-3 col-md-8"><%= message[:content] %>
            <% if message[:project] %>
              <%= link_to message[:project].title, message[:project] %>
            <% end %></p>
          <% end %>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger col-sm-offset-3 col-md-8"><%= alert %></p>
        <% end %>

        <%= yield %>

      </div>
    </div>
  </body>
</html>